---

- name: Stop if kubeadm mode is enabled but custom_flag set
  assert:
    that: >
      (apiserver_custom_flags|d([])|length > 0 or
      controller_mgr_custom_flags|d([])|length > 0 or
      scheduler_custom_flags|d([])|length > 0
    msg: "controlplane *_custom_flag with kubeadm not working, use kube_kubeadm_*_extra_args variables"
  when: kubeadm_enabled

- name: Stop if kubeadm mode is disabled but kubeadm_extra_args set
  assert:
    that: >
      ( kube_kubeadm_apiserver_extra_args is defined and kube_kubeadm_apiserver_extra_args.keys()|length > 0 ) or
      ( kube_kubeadm_controller_extra_args is defined and kube_kubeadm_controller_extra_args.keys()|length > 0 ) or
      ( kube_kubeadm_scheduler_extra_args is defined and kube_kubeadm_scheduler_extra_args.keys()|length > 0 )
    msg: "kube_kubeadm_*_extra_args with non-kubeadm install mode not working, use controlplane *_custom_flag variables"
  when: not kubeadm_enabled
